version: '3.5'
services:
  api1: &api
    image: api
    hostname: api1
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rinha
      - NODE_ENV=production
    depends_on:
      - postgres
    expose:
      - '8080'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  api2: # API - Instância 02
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'

volumes:
  postgres_data:
